name: GPSPlugin
main: org.tnjs.GPSPlugin.GPSPlugin
version: 1.1.2
api-version: 1.16
author: TNJS
commands:
  gps:
    description: Get a GPS compass pointing to coordinates
    usage: /gps <x> <z>
  reroute:
    description: Change the destination of your GPS compass
    usage: /reroute <x> <z>

permissions:
  gps.use:
    description: "Allows the player to use /gps and /reroute commands"
    default: true
